- name: Install Node App
  hosts: aula
  become: yes
  vars:
    path_app: /usr/app
  tasks:
    - name: 1. Create directory
      file:
        path: "{{path_app}}"
        state: directory
        mode: 0755

    - name: 2. Install unzip dependency
      package:
        name:
          - unzip
        state: present
    - name: 3. Download and unzip
      unarchive:
        src: https://github.com/bgsouza/app_node2/archive/master.zip
        dest: "{{path_app}}"
        remote_src: yes

    # - name: 4. Compile app

    # - name: 5. Install manager node pm2

    # - name: 6. Run app