---
- name: Upload Simple File
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    file_src: teste.txt
    file_dest: /usr/src
    mode: 0777
  tasks:
    - name: Upload file
      template:
        src:  "{{file_src}}"
        dest: "{{file_dest}}"
        mode: 0777
      register: upload_file